int  Camerabrowser1callback(int item,int i,void *Tmp) ;
void  Camerabrowser1init(DIX *X,void *pt) ;
int  Camerabutton1callback(int butno,int i,void *Tmp) ;
void  Camerabutton1init(DIN *B,void *pt) ;
int  Camerabrowser2callback(int item,int i,void *Tmp) ;
void  Camerabrowser2init(DIY *Y,void *pt) ;
int  Camerasplbutton1callback(int butno,int i,void *Tmp) ;
void  Camerasplbutton1init(DIL *B,void *pt) ;
int Camerainit(void *Tmp) ;
int Cameracleanup(void *Tmp) ;
int CameraCallBack(void *Tmp,void *tmp) ;
int CameraResizeCallBack(void *Tmp) ;
