void kgviewgbox1init(int i,void *Tmp) ;
int  kgviewsplbutton1callback(int butno,int i,void *Tmp) ;
void  kgviewsplbutton1init(DIL *B,void *pt) ;
int  kgviewbrowser1callback(int item,int i,void *Tmp) ;
void  kgviewbrowser1init(DIY *X,void *pt) ;
int  kgviewbrowser2callback(int item,int i,void *Tmp) ;
void  kgviewbrowser2init(DIY *Y,void *pt) ;
int  kgviewbutton1callback(int butno,int i,void *Tmp) ;
void  kgviewbutton1init(DIN *B,void *pt) ;
int  kgviewdslide1callback(int val,int i,void *Tmp) ;
int  kgviewbutton2callback(int butno,int i,void *Tmp) ;
void  kgviewbutton2init(DIN *B,void *pt) ;
int  kgviewbutton3callback(int butno,int i,void *Tmp) ;
void  kgviewbutton3init(DIN *B,void *pt) ;
int  kgviewbutton4callback(int butno,int i,void *Tmp) ;
void  kgviewbutton4init(DIN *B,void *pt) ;
int  kgviewbrowser3callback(int item,int i,void *Tmp) ;
void  kgviewbrowser3init(DIX *X,void *pt) ;
int  kgviewbutton5callback(int butno,int i,void *Tmp) ;
void  kgviewbutton5init(DIN *B,void *pt) ;
int  kgviewbrowser4callback(int item,int i,void *Tmp) ;
void  kgviewbrowser4init(DIY *Y,void *pt) ;
int  kgviewbutton6callback(int butno,int i,void *Tmp) ;
void  kgviewbutton6init(DIN *B,void *pt) ;
int kgviewinit(void *Tmp) ;
int kgviewcleanup(void *Tmp) ;
int kgviewCallBack(void *Tmp,void *tmp) ;
int kgviewResizeCallBack(void *Tmp) ;
